FROM ubuntu:14.04
MAINTAINER Rhys

RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends php5-cli

# Make image smaller
RUN DEBIAN_FRONTEND=noninteractive apt-get purge -y --auto-remove

COPY ./dockerize /usr/local/bin/dockerize

VOLUME /var/apps/ecomm
WORKDIR /var/apps/ecomm
