version: '2'
services:
    mq:
        image: rabbitmq:3-management
        ports: 
            - "8989:15672"
    elasticsearch:
        image: elasticsearch:2.3
    logstash:
        build:
            context: .
            dockerfile: Dockerfile-logstash
        volumes:
        - .:/var/apps/logstash
        entrypoint: 
            - "/usr/local/bin/dockerize" 
            - "-wait" 
            - "tcp://mq:5672"
            - "-wait" 
            - "tcp://elasticsearch:9200"
        command: ["logstash", "-f", "/var/apps/logstash/logstash.conf"]
        depends_on:
            - mq
            - elasticsearch
        links:
            - mq
            - elasticsearch
    kibana:
        build:
            context: .
            dockerfile: Dockerfile-kibana
        entrypoint: 
            - "/usr/local/bin/dockerize" 
            - "-wait" 
            - "tcp://elasticsearch:9200"
        command: kibana
        ports:
            - "8990:5601"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
    generate:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/generate.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    orders:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/orders.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    pos:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/pos.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    products:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/products.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
