version: '2'
services:
    mq:
        image: rabbitmq:3-management
        ports: 
            - "8989:15672"
    generate:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/generate.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    orders:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/orders.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    pos:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/pos.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
    products:
        build:
            context: .
            dockerfile: Dockerfile-app
        entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mq:5672"]
        command: ["/usr/bin/php", "/var/apps/ecomm/products.php"]
        volumes:
            - .:/var/apps/ecomm
        depends_on:
            - mq
        links:
            - mq
